# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

# see https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#secret-variables
variables:
  KHULNASOFT_KEY: $(khulnasoftKey)
  KHULNASOFT_SECRET: $(khulnasoftSecret)

jobs:
- job: A
  steps:
  - task: tfsec@1
- job: B
  steps:
  - task: trivy@1
    #displayName: vulnerabilities
    inputs:
      image: liamg/thisisfine
      khulnasoftKey: $(KHULNASOFT_KEY)
      #khulnasoftSecret: $(KHULNASOFT_SECRET)
      #devMode: True
